dependencies:
  - name: inv-svc-solution-hst
    version: 0.0.1
    repository: >-
      https://artifactory-tools.htalukder-classic-cluster-2bef1f4b4097001da9502000c44fc2b2-0000.us-east.containers.appdomain.cloud/artifactory/generic-local/dev-ht
